name: Portfolio CI/CD

# Wann soll die Pipeline starten?
on:
  push:
    branches: [ main ]  # Bei jedem Push auf den main-branch
  pull_request:
    branches: [ main ]  # Bei jedem Pull Request

jobs:
  # JOB 1: Backend testen & bauen
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Docker Image bauen (Backend)
        run: docker build ./portfolio_backend -t portfolio-backend:test

  # JOB 2: Frontend testen & bauen
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Docker Image bauen (Frontend)
        run: docker build ./portfolio_frontend -t portfolio-frontend:test
