name: Docker Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Hier setzen wir die Variable global für den ganzen Workflow
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # V4 ist aktuell korrekt, die Warnung verschwindet durch die env-Variable oben

      # 1. Backend Check
      - name: Build Backend Image
        run: |
          cd portfolio_backend
          docker build . -t backend:latest

      # 2. Frontend Check
      - name: Build Frontend Image
        run: |
          cd portfolio_frontend
          docker build . -t portfolio-frontend:latest
